In [1]:
import numpy as np
import pandas as pd

columns = ['user_id', 'item_id', 'rating', 'timestamp', 'title', 'people', 'country', 'genre']
dataset = pd.read_csv("naver_movie_dataset.csv", names=columns)

In [2]:
dataset

,user_id,item_id,rating,timestamp,title,people,country,genre
0,0,2,7,1494128040,빽 투 더 퓨쳐 2,"['마이클 J. 폭스', '크리스토퍼 로이드', '리 톰슨', '토머스 F. 윌슨'...",['미국'],"['SF', '코미디']"
1,0,3,7,1467529800,빽 투 더 퓨쳐 3,"['마이클 J. 폭스', '크리스토퍼 로이드', '메리 스틴버겐', '토머스 F. ...",['미국'],"['서부', 'SF', '판타지', '코미디']"
2,0,16,9,1513344120,이티,"['헨리 토마스', '디 월리스', '피터 코요테', '로버트 맥노튼', '드류 베...",['미국'],"['판타지', 'SF', '모험', '가족']"
3,0,19,9,1424497980,록키,"['실베스터 스탤론', '탈리아 샤이어', '버트 영', '칼 웨더스', '버제스 ...",['미국'],"['드라마', '액션']"
4,0,20,7,1427627340,록키 2,"['실베스터 스탤론', '탈리아 샤이어', '버트 영', '칼 웨더스', '버제스 ...",['미국'],"['드라마', '액션']"
...,...,...,...,...,...,...,...,...
57407,2140,431,5,1145626620,몽중인,"['주윤발', '양설의', '임청하', '금연령', '관산', '정수일', '임총']",['홍콩'],['멜로/로맨스']
57408,2140,452,6,1150025820,파리 대왕,"['발타자 게티', '크리스 퍼', '다누엘 피폴리', '제임스 뱃지 데일', '앤...",['미국'],"['드라마', '모험', '스릴러']"
57409,2140,483,7,1153595280,아이다호,"['리버 피닉스', '키아누 리브스', '제임스 루소', '윌리암 리처트', '로드...",['미국'],['드라마']
57410,2140,537,9,1144247640,종횡사해,"['주윤발', '장국영', '종초홍', '증강', '주강']",['홍콩'],"['드라마', '액션', '범죄']"
57411,2140,538,1,1152619320,와일드 오키드,"['미키 루크', '캐리 오티스', '재클린 비셋']",['미국'],"['드라마', '에로']"

In [3]:
dataset1 = dataset[['item_id','title']]
dataset1.drop_duplicates(inplace=True, subset='item_id', keep="last")
products_dict = dataset1.groupby('item_id')['title'].apply(list).to_dict()
products_dict

C:\Users\LMS\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

{0: ['시네마 천국'],
 1: ['빽 투 더 퓨쳐'],
 2: ['빽 투 더 퓨쳐 2'],
 3: ['빽 투 더 퓨쳐 3'],
 4: ['스타워즈 에피소드 4 - 새로운 희망'],
 5: ['스타워즈 에피소드 5 - 제국의 역습'],
 6: ['스타워즈 에피소드 6 - 제다이의 귀환'],
 7: ['슈퍼맨'],
 8: ['슈퍼맨 2'],
 9: ['슈퍼맨 4 - 최강의 적'],
 10: ['다이 하드'],
 11: ['킹콩'],
 12: ['금지된 장난'],
 13: ['타워링'],
 14: ['나 홀로 집에'],
 15: ['셰인'],
 16: ['이티'],
 17: ['내일을 향해 쏴라'],
 18: ['바람과 함께 사라지다'],
 19: ['록키'],
 20: ['록키 2'],
 21: ['록키 3'],
 22: ['록키 4'],
 23: ['록키 5'],
 24: ['리썰 웨폰'],
 25: ['리썰 웨폰 2'],
 26: ['터미네이터'],
 27: ['죠스'],
 28: ['죠스 2'],
 29: ['레이더스'],
 30: ['인디아나 존스'],
 31: ['인디아나 존스 - 최후의 성전'],
 32: ['코만도'],
 33: ['에이리언'],
 34: ['에이리언 2'],
 35: ['플래툰'],
 36: ['구니스'],
 37: ['포세이돈 어드벤쳐'],
 38: ['콰이강의 다리'],
 39: ['나바론 요새'],
 40: ['나바론 요새 2'],
 41: ['킬링 필드'],
 42: ['빠삐용'],
 43: ['스팅'],
 44: ['죽은 시인의 사회'],
 45: ['그렘린'],
 46: ['싸이코'],
 47: ['자이언트'],
 48: ['라 밤바'],
 49: ['람보'],
 50: ['람보 2'],
 51: ['람보 3'],
 52: ['벤허'],
 53: ['끝없는 사랑'],
 54: ['프레데터'],
 55: ['프레데터 2'],
 56: ['별들의 고향'],
 57: ['십계'],
 58: ['엑소시스트'],
 59: ['오멘'],
 60: ['영자의 전성시대'],
 61: ['언터처블'],
 62: ['황야의 무법자'],
 63: ['OK 목장의 결투'],
 64: ['대부'],
 65: ['대부 2'],
 66: ['티파니에서 아침을'],
 67: ['폴리스 아카데미'],
 68: ['폴리스 아카데미 2 - 첫임무'],
 69: ['폴리스 아카데미 3 - 재훈련'],
 70: ['미션'],
 71: ['토요일 밤의 열기'],
 72: ['파이어폭스'],
 73: ['그리스'],
 74: ['챔프'],
 75: ['네버엔딩 스토리'],
 76: ['러브 스토리'],
 77: ['마이 웨이'],
 78: ['고스트버스터즈'],
 79: ['고스트버스터즈 2'],
 80: ['남과 여'],
 81: ['탑건'],
 82: ['로마의 휴일'],
 83: ['사운드 오브 뮤직'],
 84: ['닥터 지바고'],
 85: ['사관과 신사'],
 86: ['사랑은 비를 타고'],
 87: ['카사블랑카'],
 88: ['아웃 오브 아프리카'],
 89: ['호소자'],
 90: ['영웅본색'],
 91: ['영웅본색 2'],
 92: ['영웅본색 3'],
 93: ['첩혈쌍웅'],
 94: ['아마데우스'],
 95: ['용형호제 2 - 비룡계획'],
 96: ['스플래쉬'],
 97: ['라붐'],
 98: ['라붐 2'],
 99: ['엘리게이터'],
 100: ['엘리게이터 2'],
 101: ['내 이름은 튜니티'],
 102: ['강시번생'],
 103: ['스타 탄생'],
 104: ['디어 헌터'],
 105: ['미드나잇 익스프레스'],
 106: ['캐논볼'],
 107: ['귀여운 여인'],
 108: ['고래 사냥'],
 109: ['고래 사냥 2'],
 110: ['펌프킨헤드'],
 111: ['정복자 펠레'],
 112: ['파울 플레이'],
 113: ['매드 맥스'],
 114: ['매드 맥스 3'],
 115: ['애정의 조건'],
 116: ['아메리칸 지골로'],
 117: ['나인 하프 위크'],
 118: ['인도로 가는 길'],
 119: ['최가박당'],
 120: ['나이트메어'],
 121: ['바보들의 행진'],
 122: ['바람 불어 좋은 날'],
 123: ['자전거 도둑'],
 124: ['로보트 태권V'],
 125: ['폴링 인 러브'],
 126: ['007 살인번호'],
 127: ['007 위기일발'],
 128: ['007 골드핑거'],
 129: ['007 선더볼 작전'],
 130: ['007 두번 산다'],
 131: ['007 카지노 로얄'],
 132: ['007과 여왕'],
 133: ['007 다이아몬드는 영원히'],
 134: ['007 죽느냐 사느냐'],
 135: ['007 황금총을 가진 사나이'],
 136: ['007 나를 사랑한 스파이'],
 137: ['007 문레이커'],
 138: ['007 유어 아이스 온리'],
 139: ['007 네버 세이 네버 어게인'],
 140: ['007 옥터퍼시'],
 141: ['007 뷰 투 어 킬'],
 142: ['007 리빙 데이라이트'],
 143: ['007 살인면허'],
 144: ['사랑과 영혼'],
 145: ['남과 북'],
 146: ['남과 북 2'],
 147: ['13일의 금요일'],
 148: ['하이 눈'],
 149: ['대통령을 만드는 사람들'],
 150: ['정무문'],
 151: ['용쟁호투'],
 152: ['맹룡과강'],
 153: ['당산대형'],
 154: ['로미오와 줄리엣'],
 155: ['돌아이'],
 156: ['13일의 금요일 4'],
 157: ['코난 - 바바리안'],
 158: ['코난 2 - 디스트로이어'],
 159: ['레드 소냐'],
 160: ['호소자 2'],
 161: ['호소자 3 - 고아유랑기'],
 162: ['호소자 6'],
 163: ['겨울 여자'],
 164: ['터미네이터 2:오리지널'],
 165: ['칵테일'],
 166: ['이장호의 외인구단'],
 167: ['지존계상'],
 168: ['컬러 오브 머니'],
 169: ['갈매기의 꿈'],
 170: ['자유부인'],
 171: ['어게인스트'],
 172: ['아파치'],
 173: ['누구를 위하여 종은 울리나'],
 174: ['뮤직 박스'],
 175: ['엠마뉴엘'],
 176: ['레드 히트'],
 177: ['로보캅'],
 178: ['로보캅 2'],
 179: ['메이저 리그'],
 180: ['핑크 팬더 4 - 핑크 팬더의 역습'],
 181: ['나자리노'],
 182: ['개 같은 내 인생'],
 183: ['돈가방을 든 수녀'],
 184: ['그날이 오면'],
 185: ['오멘 2'],
 186: ['스트리트 오브 파이어'],
 187: ['7년만의 외출'],
 188: ['레인 맨'],
 189: ['내츄럴'],
 190: ['더티 댄싱'],
 191: ['북북서로 진로를 돌려라'],
 192: ['늑대와 춤을'],
 193: ['다이 하드 2'],
 194: ['다크맨'],
 195: ['도마단'],
 196: ['모던 타임즈'],
 197: ['해리가 샐리를 만났을 때'],
 198: ['미지와의 조우'],
 199: ['배트맨'],
 200: ['노틀담의 꼽추'],
 201: ['노틀담의 꼽추'],
 202: ['베스트 키드'],
 203: ['델마와 루이스'],
 204: ['돌아오지 않는 강'],
 205: ['뉴욕세남자와아기'],
 206: ['마네킨'],
 207: ['마네킨 2'],
 208: ['맨발의 청춘'],
 209: ['미드나잇 카우보이'],
 210: ['스위치'],
 211: ['엑설런트 어드벤쳐'],
 212: ['니키타'],
 213: ['백야'],
 214: ['보디 히트'],
 215: ['스탠 바이 미'],
 216: ['마농의 샘 2'],
 217: ['뜨거운 것이 좋아'],
 218: ['로맨싱 스톤'],
 219: ['부시맨'],
 220: ['부시맨 2'],
 221: ['부시맨 4 - 크레이지 홍콩'],
 222: ['불의 전차'],
 223: ['브이 - 5부작 미니시리즈'],
 224: ['사막의 라이온'],
 225: ['복수'],
 226: ['투씨'],
 227: ['간디'],
 228: ['시티 라이트'],
 229: ['나의 성공의 비밀'],
 230: ['나이트호크'],
 231: ['프로젝트 A'],
 232: ['프로젝트A 2 : A계획 속집'],
 233: ['너에게로 또다시'],
 234: ['마이키 이야기'],
 235: ['사랑의 행로'],
 236: ['마지막 황제'],
 237: ['모정'],
 238: ['7일간의 사랑'],
 239: ['사랑할 때와 이별할 때'],
 240: ['살인광 시대'],
 241: ['쉘부르의 우산'],
 242: ['사브리나'],
 243: ['서부 개척사'],
 244: ['스카페이스'],
 245: ['스카페이스'],
 246: ['엘비라 마디간'],
 247: ['신의 아들'],
 248: ['아라비아의 로렌스'],
 249: ['석양의 무법자'],
 250: ['암흑가의 두 사람'],
 251: ['빌리티스'],
 252: ['위대한 독재자'],
 253: ['레베카'],
 254: ['무숙자'],
 255: ['황야의 7인'],
 256: ['베드룸 윈도우'],
 257: ['세 남자와 아기 2'],
 258: ['아리랑'],
 259: ['브로드캐스트 뉴스'],
 260: ['사의 찬미'],
 261: ['소오강호'],
 262: ['신사는 금발을 좋아한다'],
 263: ['철십자 훈장'],
 264: ['아틱 히트'],
 265: ['사이공'],
 266: ['아이큐 제로'],
 267: ['브룩클린으로 가는 마지막 비상구'],
 268: ['아미티빌의 저주'],
 269: ['알제리 전투'],
 270: ['에덴의 동쪽'],
 271: ['어벤저'],
 272: ['워킹 걸'],
 273: ['양철북'],
 274: ['크로커다일 던디'],
 275: ['크로커다일 던디 2'],
 276: ['나일의 대모험'],
 277: ['그리스도 최후의 유혹'],
 278: ['플래시댄스'],
 279: ['피라미드의 공포'],
 280: ['남부군'],
 281: ['에프 엑스'],
 282: ['킹콩'],
 283: ['비버리 힐스 캅'],
 284: ['비버리 힐스 캅 2'],
 285: ['라임라이트'],
 286: ['서울 무지개'],
 287: ['선샤인'],
 288: ['신의 아그네스'],
 289: ['작은 신의 아이들'],
 290: ['드라이빙 미스 데이지'],
 291: ['레비아탄'],
 292: ['레이디호크'],
 293: ['맥아더'],
 294: ['쇼처럼 즐거운 인생은 없다'],
 295: ['변강쇠'],
 296: ['뽕'],
 297: ['산딸기'],
 298: ['장군의 아들'],
 299: ['씨받이'],
 300: ['어우동'],
 301: ['바보 선언'],
 302: ['삼손과 데릴라'],
 303: ['성 리수일뎐'],
 304: ['수업료'],
 305: ['엔젤 하트'],
 306: ['역마차'],
 307: ['영광의 탈출'],
 308: ['아빠는 출장 중'],
 309: ['해바라기'],
 310: ['예스 마담 - 황가사저'],
 311: ['영혼의 목걸이'],
 312: ['닌자 거북이'],
 313: ['취권'],
 314: ['성룡의 미라클'],
 315: ['새벽의 7인'],
 316: ['실베스타 스텔론의 탈옥'],
 317: ['매시'],
 318: ['등대여명'],
 319: ['마유미'],
 320: ['오즈의 마법사'],
 321: ['총알탄 사나이'],
 322: ['총알탄 사나이 2'],
 323: ['열차 안의 낯선 자들'],
 324: ['졸업'],
 325: ['사랑을 위하여'],
 326: ['실버 스트릭'],
 327: ['올리버'],
 328: ['야수의 최후'],
 329: ['연산군'],
 330: ['연산군'],
 331: ['옛날 옛적 서부에서'],
 332: ['전함 포템킨'],
 333: ['제3의 사나이'],
 334: ['은행털이와 아빠와 나'],
 335: ['장미의 이름'],
 336: ['젊은이의 양지'],
 337: ['붉은 수수밭'],
 338: ['전망 좋은 방'],
 339: ['열혈천사'],
 340: ['차타레 부인의 사랑'],
 341: ['매춘'],
 342: ['미드나잇 런'],
 343: ['미져리'],
 344: ['세븐 싸인'],
 345: ['우먼 인 레드'],
 346: ['왕과 나'],
 347: ['여학생'],
 348: ['18 어게인'],
 349: ['저 하늘에 태양이'],
 350: ['지옥의 묵시록'],
 351: ['비 오는 날 수채화'],
 352: ['콘돌'],
 353: ['양들의 침묵'],
 354: ['성춘향'],
 355: ['성춘향'],
 356: ['우리 집의 낙원'],
 357: ['벤지'],
 358: ['태양은 가득히'],
 359: ['붉은 10월'],
 360: ['작은 사랑의 멜로디'],
 361: ['블랙 레인'],
 362: ['빙점 81'],
 363: ['브레이크아웃'],
 364: ['1941'],
 365: ['블러드 심플'],
 366: ['불가사리'],
 367: ['드라큐라'],
 368: ['용적심'],
 369: ['마이 튜터'],
 370: ['베스트 오브 더 베스트'],
 371: ['모스크바는 눈물을 믿지 않는다'],
 372: ['지존무상'],
 373: ['아비정전'],
 374: ['제트'],
 375: ['쟈니 핸섬'],
 376: ['라스트 콘서트'],
 377: ['오발탄'],
 378: ['영환도사'],
 379: ['노 머시'],
 380: ['대부 3'],
 381: ['웨스트 사이드 스토리'],
 382: ['비정성시'],
 383: ['이유없는 반항'],
 384: ['야행'],
 385: ['베를린 천사의 시'],
 386: ['그린 카드'],
 387: ['애마부인'],
 388: ['애마부인 2'],
 389: ['애마부인 3'],
 390: ['살바도르'],
 391: ['전쟁과 평화'],
 392: ['위대한 개츠비'],
 393: ['수잔 브링크의 아리랑'],
 394: ['접시꽃 당신'],
 395: ['제17 포로수용소'],
 396: ['지붕 위의 바이올린'],
 397: ['지상에서 영원으로'],
 398: ['미워도 다시 한번 1부'],
 399: ['페노미나'],
 400: ['나쁜 피'],
 401: ['빅'],
 402: ['버스 정류장'],
 403: ['천국의 문'],
 404: ['젊은 날의 초상'],
 405: ['7인의 사무라이'],
 406: ['새엄마는 외계인'],
 407: ['캠퍼스 군단'],
 408: ['그레이스토크'],
 409: ['윌로우'],
 410: ['이어 오브 드래곤'],
 411: ['이창'],
 412: ['천국보다 낯선'],
 413: ['첩혈가두'],
 414: ['촉산'],
 415: ['크레이머 대 크레이머'],
 416: ['7월 4일생'],
 417: ['코브라'],
 418: ['태양의 제국'],
 419: ['천금을 마다한 사나이'],
 420: ['좋은 친구들'],
 421: ['커튼 클럽'],
 422: ['트윈스'],
 423: ['도어즈'],
 424: ['특전 유보트'],
 425: ['복카치오 91'],
 426: ['홀리데이 킬러'],
 427: ['실버라도'],
 428: ['나의 사랑 나의 신부'],
 429: ['적과의 동침'],
 430: ['겨울 여자 2'],
 431: ['몽중인'],
 432: ['복수무정'],
 433: ['비처럼 음악처럼'],
 434: ['인어 공주'],
 435: ['천녀유혼'],
 436: ['타이페이 스토리'],
 437: ['패튼 대전차 군단'],
 438: ['포스트맨은 벨을 두 번 울린다'],
 439: ['제7의 봉인'],
 440: ['사랑의 용기'],
 441: ['천녀유혼 2 - 인간도'],
 442: ['뻐꾸기 둥지 위로 날아간 새'],
 443: ['사랑과 추억'],
 444: ['천사와 사랑을'],
 445: ['사랑과 슬픔의 맨하탄'],
 446: ['블랙 썬데이'],
 447: ['컬러 퍼플'],
 448: ['마지막 보이 스카웃'],
 449: ['파리에서의 마지막 탱고'],
 450: ['프라하의 봄'],
 451: [nan],
 452: ['파리 대왕'],
 453: ['파리 텍사스'],
 454: ['애마부인 4'],
 455: ['애마부인 5'],
 456: ['애마부인 6'],
 457: ['코러스 라인'],
 458: ['월 스트리트'],
 459: ['더티 해리'],
 460: ['더티 해리 2 - 이것이 법이다'],
 461: ['더티 해리 3 - 집행자'],
 462: ['더티 해리 4 - 써든 임팩트'],
 463: ['48시간'],
 464: ['48시간 2'],
 465: ['집시의 시간'],
 466: ['비치 바니즈'],
 467: ['자전거를 타고 온 연인'],
 468: ['나이트메어 2 - 프레디의 복수'],
 469: ['나이트메어 3 - 꿈의 전사'],
 470: ['나이트메어 4 - 꿈의 지배자'],
 471: ['나이트메어 5 - 꿈꾸는 아이들'],
 472: ['나이트메어 6 - 프레디 죽다'],
 473: ['JFK'],
 474: ['연인'],
 475: ['원초적 본능'],
 476: ['불을 찾아서'],
 477: ['비목'],
 478: ['폴리스 스토리'],
 479: ['파리 애마'],
 480: ['블루 라군'],
 481: ['사랑의 파도'],
 482: ['적 그리고 사랑 이야기'],
 483: ['아이다호'],
 484: ['나이아가라'],
 485: ['달마가 동쪽으로 간 까닭은?'],
 486: ['기쁜 우리 젊은 날'],
 487: ['사랑의 기적'],
 488: ['배트 21'],
 489: ['가을 날의 동화'],
 490: ['프랭키와 쟈니'],
 491: ['하타리'],
 492: ['애들이 줄었어요'],
 493: ['반도레로'],
 494: ['소권괴초 2 - 용등호약'],
 495: ['수탉'],
 496: [nan],
 497: ['유혹은 밤 그림자처럼'],
 498: ['벅시'],
 499: ['토탈 리콜'],
 500: ['김의 전쟁'],
 501: ['애란'],
 502: ['모두가 죽이고 싶던 여자'],
 503: ['이자벨 에버하트'],
 504: ['마이키 이야기 2'],
 505: ['우묵배미의 사랑'],
 506: ['장군의 아들 2'],
 507: ['장군의 아들 3'],
 508: ['딕 트레이시'],
 509: ['우뢰매'],
 510: ['내 사랑 동키호테'],
 511: ['백경'],
 512: ['영심이'],
 513: ['영구와 땡칠이'],
 514: ['블랙 에이리언'],
 515: ['밤 그리고 도시'],
 516: ['깃발 없는 기수'],
 517: ['깊고 푸른 밤'],
 518: ['아파치'],
 519: ['베를린 리포트'],
 520: ['꿈'],
 521: ['변강쇠 2'],
 522: ['칠수와 만수'],
 523: ['블루 하트'],
 524: ['쿼바디스'],
 525: ['마지막 사랑'],
 526: ['특경도룡'],
 527: ['천국으로 가는 장의사'],
 528: ['새'],
 529: ['죽음의 표적'],
 530: ['칼리굴라'],
 531: ['비공개'],
 532: ['부메랑'],
 533: ['더블 반담'],
 534: ['드레스드 투 킬'],
 535: ['모스키토 코스트'],
 536: ['베로니카의 이중 생활'],
 537: ['종횡사해'],
 538: ['와일드 오키드'],
 539: ['헨리 5세'],
 540: ['물 위를 걷는 여자'],
 541: ['깜보'],
 542: ['엠마뉴엘 3 - 굿바이 엠마뉴엘'],
 543: ['나일 살인사건'],
 544: ['개그맨'],
 545: ['깊은 밤 깊은 곳에'],
 546: ['개인 교수 2'],
 547: ['위험한 정사'],
 548: ['레이디 인 블랙'],
 549: ['8번가의 기적'],
 550: ['바람과 라이온'],
 551: ['피고인'],
 552: ['나의 밤은 당신의 낮보다 아름답다'],
 553: ['아제 아제 바라아제'],
 554: ['고령가 소년 살인사건'],
 555: ['뻘'],
 556: ['따귀 일곱대'],
 557: ['공작왕'],
 558: ['새앙쥐 상륙 작전'],
 559: ['비너스의 여름시'],
 560: ['로드 하우스'],
 561: ['가위손'],
 562: ['피셔 킹'],
 563: ['원 + 씩스'],
 564: ['베어'],
 565: ['누가 로져 래빗을 모함했나'],
 566: ['져지 걸'],
 567: ['공룡 선생'],
 568: ['카르멘'],
 569: ['마지막 전투'],
 570: ['마루타'],
 571: ['투 문 정션'],
 572: ['블레이드 러너'],
 573: ['섹스 거짓말 그리고 비디오테이프'],
 574: ['전선 위의 참새'],
 575: ['원스 어폰 어 타임 인 아메리카'],
 576: ['블루 스틸'],
 577: ['한니발'],
 578: ['킹콩 2'],
 579: ['학창 보고서'],
 580: ['비틀즈: 하드 데이즈 나이트'],
 581: ['분노의 역류'],
 582: ['하바나'],
 583: ['사랑이 머무는 곳에'],
 584: ['할리와 말보로 맨'],
 585: ['파리의 여인'],
 586: ['19번째 남자'],
 587: ['폭주 기관차']}

In [4]:
products_dict[0]

['시네마 천국']

In [5]:
num_user = dataset['user_id'].value_counts()
# df 형식으로 변환
num_user = pd.DataFrame({'user_id':num_user.index, 'counts':num_user.values})
num_user

      user_id  counts
0         323     322
1          72     268
2          52     260
3         514     245
4          45     223
...       ...     ...
2040     1638      10
2041     1670      10
2042     1766      10
2043     1549      10
2044     1067      10

[2045 rows x 2 columns]

In [6]:
# 유일한 VOD ID 값
num_vod = dataset['item_id'].value_counts()
# df 형식으로 변환
num_vod = pd.DataFrame({'item_id':num_vod.index, 'counts':num_vod.values})
num_vod
# 491539 중 시청한 VOD 수 : 1034

     item_id  counts
0        164    1111
1         44     999
2        561     828
3          0     799
4         64     787
..       ...     ...
583      563       1
584      467       1
585      355       1
586      503       1
587      169       1

[588 rows x 2 columns]

In [7]:
# 시청 횟수가 5회 이상인 유저 수
num_user_5 = num_user[num_user['counts']>4]
num_user_5
# 약 5만명의 user 중 시청 횟수 5이상은 2만명

      user_id  counts
0         323     322
1          72     268
2          52     260
3         514     245
4          45     223
...       ...     ...
2040     1638      10
2041     1670      10
2042     1766      10
2043     1549      10
2044     1067      10

[2045 rows x 2 columns]

In [8]:
# 시청 횟수가 5회 이상인 VOD 
num_vod_5 = num_vod[num_vod['counts']>4]
num_vod_5
# 1034개 VOD 중 시청 횟수 5이상은 994개

     item_id  counts
0        164    1111
1         44     999
2        561     828
3          0     799
4         64     787
..       ...     ...
508      425       5
509      146       5
510      456       5
511      369       5
512      454       5

[513 rows x 2 columns]

In [9]:
# 5회 이상 시청한 이력만 추출하기
check = dataset['user_id'].isin(num_user_5['user_id'])
df = dataset[dataset['user_id'].isin(num_user_5['user_id'])]
df

,user_id,item_id,rating,timestamp,title,people,country,genre
0,0,2,7,1494128040,빽 투 더 퓨쳐 2,"['마이클 J. 폭스', '크리스토퍼 로이드', '리 톰슨', '토머스 F. 윌슨'...",['미국'],"['SF', '코미디']"
1,0,3,7,1467529800,빽 투 더 퓨쳐 3,"['마이클 J. 폭스', '크리스토퍼 로이드', '메리 스틴버겐', '토머스 F. ...",['미국'],"['서부', 'SF', '판타지', '코미디']"
2,0,16,9,1513344120,이티,"['헨리 토마스', '디 월리스', '피터 코요테', '로버트 맥노튼', '드류 베...",['미국'],"['판타지', 'SF', '모험', '가족']"
3,0,19,9,1424497980,록키,"['실베스터 스탤론', '탈리아 샤이어', '버트 영', '칼 웨더스', '버제스 ...",['미국'],"['드라마', '액션']"
4,0,20,7,1427627340,록키 2,"['실베스터 스탤론', '탈리아 샤이어', '버트 영', '칼 웨더스', '버제스 ...",['미국'],"['드라마', '액션']"
...,...,...,...,...,...,...,...,...
57407,2140,431,5,1145626620,몽중인,"['주윤발', '양설의', '임청하', '금연령', '관산', '정수일', '임총']",['홍콩'],['멜로/로맨스']
57408,2140,452,6,1150025820,파리 대왕,"['발타자 게티', '크리스 퍼', '다누엘 피폴리', '제임스 뱃지 데일', '앤...",['미국'],"['드라마', '모험', '스릴러']"
57409,2140,483,7,1153595280,아이다호,"['리버 피닉스', '키아누 리브스', '제임스 루소', '윌리암 리처트', '로드...",['미국'],['드라마']
57410,2140,537,9,1144247640,종횡사해,"['주윤발', '장국영', '종초홍', '증강', '주강']",['홍콩'],"['드라마', '액션', '범죄']"
57411,2140,538,1,1152619320,와일드 오키드,"['미키 루크', '캐리 오티스', '재클린 비셋']",['미국'],"['드라마', '에로']"

In [10]:
df = df.sort_values(by='user_id')
#df.to_csv("data_user.csv")
df

,user_id,item_id,rating,timestamp,title,people,country,genre
0,0,2,7,1494128040,빽 투 더 퓨쳐 2,"['마이클 J. 폭스', '크리스토퍼 로이드', '리 톰슨', '토머스 F. 윌슨'...",['미국'],"['SF', '코미디']"
61,0,350,8,1449368340,지옥의 묵시록,"['말론 브란도', '로버트 듀발', '마틴 쉰', '프레드릭 포레스트', '샘 바...",['미국'],"['드라마', '액션', '전쟁']"
60,0,347,6,1504613460,여학생,"['소피 마르소', '뱅상 랭동', '엘리자베스 비탈리', '장 클로드 레궈이', ...","['이탈리아', '프랑스']","['멜로/로맨스', '코미디']"
59,0,343,9,1426164480,미져리,"['제임스 칸', '캐시 베이츠', '프란시스 스턴하겐', '리차드 판스워스']",['미국'],"['드라마', '스릴러', '공포']"
58,0,342,6,1459256820,미드나잇 런,"['로버트 드 니로', '찰스 그로딘', '야펫 코토', '존 애쉬튼', '데니스 ...",['미국'],"['액션', '스릴러', '모험', '코미디']"
...,...,...,...,...,...,...,...,...
57398,2140,229,5,1141821000,나의 성공의 비밀,"['마이클 J. 폭스', '헬렌 슬레이터', '리처드 조던', '마가렛 휘튼', '...",['미국'],['코미디']
57397,2140,227,7,1153830240,간디,"['벤 킹슬리', '캔디스 버겐', '에드워드 폭스', '존 길구드', '트레버 하...","['미국', '영국']",['드라마']
57410,2140,537,9,1144247640,종횡사해,"['주윤발', '장국영', '종초홍', '증강', '주강']",['홍콩'],"['드라마', '액션', '범죄']"
57403,2140,360,3,1150058040,작은 사랑의 멜로디,"['마크 레스터', '트레이시 하이드', '잭 와일드', '로이 키니어', '켄 존...",['영국'],"['멜로/로맨스', '드라마', '코미디']"
57411,2140,538,1,1152619320,와일드 오키드,"['미키 루크', '캐리 오티스', '재클린 비셋']",['미국'],"['드라마', '에로']"

In [11]:
df_list = df.groupby('user_id')['item_id'].apply(list)
# df_list.to_csv("user_vod.csv")
df_list

user_id
0       [2, 350, 347, 343, 342, 340, 324, 314, 309, 28...
1       [572, 81, 561, 192, 147, 88, 55, 85, 50, 49, 4...
2       [352, 338, 332, 308, 300, 299, 291, 290, 285, ...
3       [376, 311, 382, 358, 357, 351, 323, 283, 291, ...
4       [88, 164, 92, 91, 228, 49, 90, 32, 26, 14, 1, ...
                              ...
2136    [586, 562, 496, 490, 473, 465, 458, 442, 420, ...
2137    [199, 133, 142, 140, 139, 132, 129, 128, 127, ...
2138    [143, 142, 141, 140, 138, 137, 135, 136, 133, ...
2139    [377, 140, 141, 374, 143, 231, 138, 142, 137, ...
2140    [483, 452, 431, 420, 418, 414, 244, 311, 276, ...
Name: item_id, Length: 2045, dtype: object

In [12]:
vec = df_list.values

In [13]:
vec

array([list([2, 350, 347, 343, 342, 340, 324, 314, 309, 281, 278, 267, 255, 248, 245, 217, 203, 197, 353, 358, 373, 380, 581, 575, 571, 565, 551, 542, 536, 505, 189, 499, 478, 475, 424, 416, 415, 407, 396, 381, 496, 188, 449, 177, 62, 57, 50, 49, 44, 43, 35, 34, 64, 27, 23, 22, 21, 20, 19, 16, 3, 178, 26, 65, 61, 71, 175, 168, 165, 164, 154, 144, 125, 66, 104, 97, 107, 88, 85, 82, 81, 79, 78, 76, 90]),
       list([572, 81, 561, 192, 147, 88, 55, 85, 50, 49, 45, 34, 28, 0, 54]),
       list([352, 338, 332, 308, 300, 299, 291, 290, 285, 248, 270, 359, 244, 241, 228, 216, 215, 214, 206, 197, 273, 371, 385, 382, 192, 572, 569, 544, 542, 539, 536, 534, 522, 377, 486, 465, 439, 435, 424, 420, 418, 405, 391, 387, 483, 182, 42, 143, 60, 56, 52, 47, 46, 43, 34, 33, 31, 30, 29, 18, 17, 175, 13, 12, 6, 5, 4, 66, 71, 16, 85, 84, 142, 141, 140, 137, 136, 135, 134, 133, 132, 138, 129, 130, 87, 111, 118, 88, 127, 128, 126, 86]),
       ...,
       list([143, 142, 141, 140, 138, 137, 135, 136, 133, 132, 130, 129, 128, 127, 126, 134]),
       list([377, 140, 141, 374, 143, 231, 138, 142, 137, 133, 135, 134, 132, 130, 129, 128, 127, 126, 136]),
       list([483, 452, 431, 420, 418, 414, 244, 311, 276, 254, 229, 227, 537, 360, 538])],
      dtype=object)

In [14]:
from gensim.models.word2vec import Word2Vec
import matplotlib.pyplot as plt
from gensim.models import Word2Vec

In [15]:
def plot_2d_graph(vocabs, xs, ys):
    plt.figure(figsize=(32, 24))
    plt.scatter(xs, ys, marker = 'o')
    for i, v in enumerate(vocabs):
        plt.annotate(v, xy=(xs[i], ys[i]))
    # plt 저장
    plt.savefig('w2v_result.png', dpi=100)

In [16]:
model = Word2Vec(vec,         # 리스트 형태의 데이터
                 sg=1,         # 0: CBOW, 1: Skip-gram
                 vector_size=100,     # 벡터 크기
                 window=2,     # 고려할 앞뒤 폭(앞뒤 3단어)
                 min_count=3,  # 사용할 단어의 최소 빈도(3회 이하 단어 무시)
                )    # 동시에 처리할 작업 수(코어 수와 비슷하게 설정)

In [17]:
model = Word2Vec(window = 10, sg = 1, hs = 0,
                 negative = 10, # for negative sampling
                 alpha=0.03, min_alpha=0.0007,
                 seed = 14)

model.build_vocab(vec, progress_per=200)

model.train(vec, total_examples = model.corpus_count, 
            epochs=10, report_delay=1)

(351608, 510030)

In [79]:
def similar_products(v, n = 6):
    
    # extract most similar products for the input vector
    ms = model.similar_by_vector(v, topn= n+1)[1:]
    
    # extract name and similarity score of the similar products
    new_ms = []
    for j in ms:
        pair = (products_dict[j[0]][0], j[1])
        new_ms.append(pair)
        
    return new_ms

In [80]:
for index, word in enumerate(model.wv.index_to_key):
    if index == 10:
        break
    print(f"word #{index}/{len(model.wv.index_to_key)} is {word}")

word #0/513 is 164
word #1/513 is 44
word #2/513 is 561
word #3/513 is 0
word #4/513 is 64
word #5/513 is 14
word #6/513 is 83
word #7/513 is 1
word #8/513 is 94
word #9/513 is 90

In [81]:
k = model.wv.most_similar(164)
k

[(258, 0.6971423625946045),
 (147, 0.629355788230896),
 (580, 0.6280428767204285),
 (94, 0.6239832043647766),
 (190, 0.6155600547790527),
 (380, 0.6065968871116638),
 (14, 0.6062377095222473),
 (154, 0.6027756929397583),
 (170, 0.6020088791847229),
 (33, 0.5992019772529602)]

In [82]:
def recommendation(num):
    rec = model.wv.most_similar(num)
    print("영화 추천 리스트\n")
    print("선택한 영화 : ", products_dict[num])
    for i in rec:
        print(products_dict[i[0]])

In [84]:
recommendation(5)

영화 추천 리스트

선택한 영화 :  ['스타워즈 에피소드 5 - 제국의 역습']
['바람과 함께 사라지다']
['타워링']
['슈퍼맨 2']
['터미네이터']
['나 홀로 집에']
['슈퍼맨']
['킹콩']
['빽 투 더 퓨쳐']
['다이 하드']
['슈퍼맨 4 - 최강의 적']

In [14]:
# 카운트 높은 상위 5개 영화
cont = num_vod_5[:5]['item_id']
for i, a in enumerate(cont):
    print(products_dict[i],':name','\t', a,':label')

['시네마 천국'] :name 	 164 :label
['빽 투 더 퓨쳐'] :name 	 44 :label
['빽 투 더 퓨쳐 2'] :name 	 561 :label
['빽 투 더 퓨쳐 3'] :name 	 0 :label
['스타워즈 에피소드 4 - 새로운 희망'] :name 	 64 :label

In [24]:
model.save('movie_w2v.model') # model 저장

In [25]:
import pickle
with open('data_dict.pkl', 'wb') as f: # dictionary 저장
    pickle.dump(products_dict,f)

In [26]:
with open('data_dict.pkl', 'rb') as f: # dictionary 불러오기
    mydict = pickle.load(f)

In [27]:
mydict

{0: ['시네마 천국'],
 1: ['빽 투 더 퓨쳐'],
 2: ['빽 투 더 퓨쳐 2'],
 3: ['빽 투 더 퓨쳐 3'],
 4: ['스타워즈 에피소드 4 - 새로운 희망'],
 5: ['스타워즈 에피소드 5 - 제국의 역습'],
 6: ['스타워즈 에피소드 6 - 제다이의 귀환'],
 7: ['슈퍼맨'],
 8: ['슈퍼맨 2'],
 9: ['슈퍼맨 4 - 최강의 적'],
 10: ['다이 하드'],
 11: ['킹콩'],
 12: ['금지된 장난'],
 13: ['타워링'],
 14: ['나 홀로 집에'],
 15: ['셰인'],
 16: ['이티'],
 17: ['내일을 향해 쏴라'],
 18: ['바람과 함께 사라지다'],
 19: ['록키'],
 20: ['록키 2'],
 21: ['록키 3'],
 22: ['록키 4'],
 23: ['록키 5'],
 24: ['리썰 웨폰'],
 25: ['리썰 웨폰 2'],
 26: ['터미네이터'],
 27: ['죠스'],
 28: ['죠스 2'],
 29: ['레이더스'],
 30: ['인디아나 존스'],
 31: ['인디아나 존스 - 최후의 성전'],
 32: ['코만도'],
 33: ['에이리언'],
 34: ['에이리언 2'],
 35: ['플래툰'],
 36: ['구니스'],
 37: ['포세이돈 어드벤쳐'],
 38: ['콰이강의 다리'],
 39: ['나바론 요새'],
 40: ['나바론 요새 2'],
 41: ['킬링 필드'],
 42: ['빠삐용'],
 43: ['스팅'],
 44: ['죽은 시인의 사회'],
 45: ['그렘린'],
 46: ['싸이코'],
 47: ['자이언트'],
 48: ['라 밤바'],
 49: ['람보'],
 50: ['람보 2'],
 51: ['람보 3'],
 52: ['벤허'],
 53: ['끝없는 사랑'],
 54: ['프레데터'],
 55: ['프레데터 2'],
 56: ['별들의 고향'],
 57: ['십계'],
 58: ['엑소시스트'],
 59: ['오멘'],
 60: ['영자의 전성시대'],
 61: ['언터처블'],
 62: ['황야의 무법자'],
 63: ['OK 목장의 결투'],
 64: ['대부'],
 65: ['대부 2'],
 66: ['티파니에서 아침을'],
 67: ['폴리스 아카데미'],
 68: ['폴리스 아카데미 2 - 첫임무'],
 69: ['폴리스 아카데미 3 - 재훈련'],
 70: ['미션'],
 71: ['토요일 밤의 열기'],
 72: ['파이어폭스'],
 73: ['그리스'],
 74: ['챔프'],
 75: ['네버엔딩 스토리'],
 76: ['러브 스토리'],
 77: ['마이 웨이'],
 78: ['고스트버스터즈'],
 79: ['고스트버스터즈 2'],
 80: ['남과 여'],
 81: ['탑건'],
 82: ['로마의 휴일'],
 83: ['사운드 오브 뮤직'],
 84: ['닥터 지바고'],
 85: ['사관과 신사'],
 86: ['사랑은 비를 타고'],
 87: ['카사블랑카'],
 88: ['아웃 오브 아프리카'],
 89: ['호소자'],
 90: ['영웅본색'],
 91: ['영웅본색 2'],
 92: ['영웅본색 3'],
 93: ['첩혈쌍웅'],
 94: ['아마데우스'],
 95: ['용형호제 2 - 비룡계획'],
 96: ['스플래쉬'],
 97: ['라붐'],
 98: ['라붐 2'],
 99: ['엘리게이터'],
 100: ['엘리게이터 2'],
 101: ['내 이름은 튜니티'],
 102: ['강시번생'],
 103: ['스타 탄생'],
 104: ['디어 헌터'],
 105: ['미드나잇 익스프레스'],
 106: ['캐논볼'],
 107: ['귀여운 여인'],
 108: ['고래 사냥'],
 109: ['고래 사냥 2'],
 110: ['펌프킨헤드'],
 111: ['정복자 펠레'],
 112: ['파울 플레이'],
 113: ['매드 맥스'],
 114: ['매드 맥스 3'],
 115: ['애정의 조건'],
 116: ['아메리칸 지골로'],
 117: ['나인 하프 위크'],
 118: ['인도로 가는 길'],
 119: ['최가박당'],
 120: ['나이트메어'],
 121: ['바보들의 행진'],
 122: ['바람 불어 좋은 날'],
 123: ['자전거 도둑'],
 124: ['로보트 태권V'],
 125: ['폴링 인 러브'],
 126: ['007 살인번호'],
 127: ['007 위기일발'],
 128: ['007 골드핑거'],
 129: ['007 선더볼 작전'],
 130: ['007 두번 산다'],
 131: ['007 카지노 로얄'],
 132: ['007과 여왕'],
 133: ['007 다이아몬드는 영원히'],
 134: ['007 죽느냐 사느냐'],
 135: ['007 황금총을 가진 사나이'],
 136: ['007 나를 사랑한 스파이'],
 137: ['007 문레이커'],
 138: ['007 유어 아이스 온리'],
 139: ['007 네버 세이 네버 어게인'],
 140: ['007 옥터퍼시'],
 141: ['007 뷰 투 어 킬'],
 142: ['007 리빙 데이라이트'],
 143: ['007 살인면허'],
 144: ['사랑과 영혼'],
 145: ['남과 북'],
 146: ['남과 북 2'],
 147: ['13일의 금요일'],
 148: ['하이 눈'],
 149: ['대통령을 만드는 사람들'],
 150: ['정무문'],
 151: ['용쟁호투'],
 152: ['맹룡과강'],
 153: ['당산대형'],
 154: ['로미오와 줄리엣'],
 155: ['돌아이'],
 156: ['13일의 금요일 4'],
 157: ['코난 - 바바리안'],
 158: ['코난 2 - 디스트로이어'],
 159: ['레드 소냐'],
 160: ['호소자 2'],
 161: ['호소자 3 - 고아유랑기'],
 162: ['호소자 6'],
 163: ['겨울 여자'],
 164: ['터미네이터 2:오리지널'],
 165: ['칵테일'],
 166: ['이장호의 외인구단'],
 167: ['지존계상'],
 168: ['컬러 오브 머니'],
 169: ['갈매기의 꿈'],
 170: ['자유부인'],
 171: ['어게인스트'],
 172: ['아파치'],
 173: ['누구를 위하여 종은 울리나'],
 174: ['뮤직 박스'],
 175: ['엠마뉴엘'],
 176: ['레드 히트'],
 177: ['로보캅'],
 178: ['로보캅 2'],
 179: ['메이저 리그'],
 180: ['핑크 팬더 4 - 핑크 팬더의 역습'],
 181: ['나자리노'],
 182: ['개 같은 내 인생'],
 183: ['돈가방을 든 수녀'],
 184: ['그날이 오면'],
 185: ['오멘 2'],
 186: ['스트리트 오브 파이어'],
 187: ['7년만의 외출'],
 188: ['레인 맨'],
 189: ['내츄럴'],
 190: ['더티 댄싱'],
 191: ['북북서로 진로를 돌려라'],
 192: ['늑대와 춤을'],
 193: ['다이 하드 2'],
 194: ['다크맨'],
 195: ['도마단'],
 196: ['모던 타임즈'],
 197: ['해리가 샐리를 만났을 때'],
 198: ['미지와의 조우'],
 199: ['배트맨'],
 200: ['노틀담의 꼽추'],
 201: ['노틀담의 꼽추'],
 202: ['베스트 키드'],
 203: ['델마와 루이스'],
 204: ['돌아오지 않는 강'],
 205: ['뉴욕세남자와아기'],
 206: ['마네킨'],
 207: ['마네킨 2'],
 208: ['맨발의 청춘'],
 209: ['미드나잇 카우보이'],
 210: ['스위치'],
 211: ['엑설런트 어드벤쳐'],
 212: ['니키타'],
 213: ['백야'],
 214: ['보디 히트'],
 215: ['스탠 바이 미'],
 216: ['마농의 샘 2'],
 217: ['뜨거운 것이 좋아'],
 218: ['로맨싱 스톤'],
 219: ['부시맨'],
 220: ['부시맨 2'],
 221: ['부시맨 4 - 크레이지 홍콩'],
 222: ['불의 전차'],
 223: ['브이 - 5부작 미니시리즈'],
 224: ['사막의 라이온'],
 225: ['복수'],
 226: ['투씨'],
 227: ['간디'],
 228: ['시티 라이트'],
 229: ['나의 성공의 비밀'],
 230: ['나이트호크'],
 231: ['프로젝트 A'],
 232: ['프로젝트A 2 : A계획 속집'],
 233: ['너에게로 또다시'],
 234: ['마이키 이야기'],
 235: ['사랑의 행로'],
 236: ['마지막 황제'],
 237: ['모정'],
 238: ['7일간의 사랑'],
 239: ['사랑할 때와 이별할 때'],
 240: ['살인광 시대'],
 241: ['쉘부르의 우산'],
 242: ['사브리나'],
 243: ['서부 개척사'],
 244: ['스카페이스'],
 245: ['스카페이스'],
 246: ['엘비라 마디간'],
 247: ['신의 아들'],
 248: ['아라비아의 로렌스'],
 249: ['석양의 무법자'],
 250: ['암흑가의 두 사람'],
 251: ['빌리티스'],
 252: ['위대한 독재자'],
 253: ['레베카'],
 254: ['무숙자'],
 255: ['황야의 7인'],
 256: ['베드룸 윈도우'],
 257: ['세 남자와 아기 2'],
 258: ['아리랑'],
 259: ['브로드캐스트 뉴스'],
 260: ['사의 찬미'],
 261: ['소오강호'],
 262: ['신사는 금발을 좋아한다'],
 263: ['철십자 훈장'],
 264: ['아틱 히트'],
 265: ['사이공'],
 266: ['아이큐 제로'],
 267: ['브룩클린으로 가는 마지막 비상구'],
 268: ['아미티빌의 저주'],
 269: ['알제리 전투'],
 270: ['에덴의 동쪽'],
 271: ['어벤저'],
 272: ['워킹 걸'],
 273: ['양철북'],
 274: ['크로커다일 던디'],
 275: ['크로커다일 던디 2'],
 276: ['나일의 대모험'],
 277: ['그리스도 최후의 유혹'],
 278: ['플래시댄스'],
 279: ['피라미드의 공포'],
 280: ['남부군'],
 281: ['에프 엑스'],
 282: ['킹콩'],
 283: ['비버리 힐스 캅'],
 284: ['비버리 힐스 캅 2'],
 285: ['라임라이트'],
 286: ['서울 무지개'],
 287: ['선샤인'],
 288: ['신의 아그네스'],
 289: ['작은 신의 아이들'],
 290: ['드라이빙 미스 데이지'],
 291: ['레비아탄'],
 292: ['레이디호크'],
 293: ['맥아더'],
 294: ['쇼처럼 즐거운 인생은 없다'],
 295: ['변강쇠'],
 296: ['뽕'],
 297: ['산딸기'],
 298: ['장군의 아들'],
 299: ['씨받이'],
 300: ['어우동'],
 301: ['바보 선언'],
 302: ['삼손과 데릴라'],
 303: ['성 리수일뎐'],
 304: ['수업료'],
 305: ['엔젤 하트'],
 306: ['역마차'],
 307: ['영광의 탈출'],
 308: ['아빠는 출장 중'],
 309: ['해바라기'],
 310: ['예스 마담 - 황가사저'],
 311: ['영혼의 목걸이'],
 312: ['닌자 거북이'],
 313: ['취권'],
 314: ['성룡의 미라클'],
 315: ['새벽의 7인'],
 316: ['실베스타 스텔론의 탈옥'],
 317: ['매시'],
 318: ['등대여명'],
 319: ['마유미'],
 320: ['오즈의 마법사'],
 321: ['총알탄 사나이'],
 322: ['총알탄 사나이 2'],
 323: ['열차 안의 낯선 자들'],
 324: ['졸업'],
 325: ['사랑을 위하여'],
 326: ['실버 스트릭'],
 327: ['올리버'],
 328: ['야수의 최후'],
 329: ['연산군'],
 330: ['연산군'],
 331: ['옛날 옛적 서부에서'],
 332: ['전함 포템킨'],
 333: ['제3의 사나이'],
 334: ['은행털이와 아빠와 나'],
 335: ['장미의 이름'],
 336: ['젊은이의 양지'],
 337: ['붉은 수수밭'],
 338: ['전망 좋은 방'],
 339: ['열혈천사'],
 340: ['차타레 부인의 사랑'],
 341: ['매춘'],
 342: ['미드나잇 런'],
 343: ['미져리'],
 344: ['세븐 싸인'],
 345: ['우먼 인 레드'],
 346: ['왕과 나'],
 347: ['여학생'],
 348: ['18 어게인'],
 349: ['저 하늘에 태양이'],
 350: ['지옥의 묵시록'],
 351: ['비 오는 날 수채화'],
 352: ['콘돌'],
 353: ['양들의 침묵'],
 354: ['성춘향'],
 355: ['성춘향'],
 356: ['우리 집의 낙원'],
 357: ['벤지'],
 358: ['태양은 가득히'],
 359: ['붉은 10월'],
 360: ['작은 사랑의 멜로디'],
 361: ['블랙 레인'],
 362: ['빙점 81'],
 363: ['브레이크아웃'],
 364: ['1941'],
 365: ['블러드 심플'],
 366: ['불가사리'],
 367: ['드라큐라'],
 368: ['용적심'],
 369: ['마이 튜터'],
 370: ['베스트 오브 더 베스트'],
 371: ['모스크바는 눈물을 믿지 않는다'],
 372: ['지존무상'],
 373: ['아비정전'],
 374: ['제트'],
 375: ['쟈니 핸섬'],
 376: ['라스트 콘서트'],
 377: ['오발탄'],
 378: ['영환도사'],
 379: ['노 머시'],
 380: ['대부 3'],
 381: ['웨스트 사이드 스토리'],
 382: ['비정성시'],
 383: ['이유없는 반항'],
 384: ['야행'],
 385: ['베를린 천사의 시'],
 386: ['그린 카드'],
 387: ['애마부인'],
 388: ['애마부인 2'],
 389: ['애마부인 3'],
 390: ['살바도르'],
 391: ['전쟁과 평화'],
 392: ['위대한 개츠비'],
 393: ['수잔 브링크의 아리랑'],
 394: ['접시꽃 당신'],
 395: ['제17 포로수용소'],
 396: ['지붕 위의 바이올린'],
 397: ['지상에서 영원으로'],
 398: ['미워도 다시 한번 1부'],
 399: ['페노미나'],
 400: ['나쁜 피'],
 401: ['빅'],
 402: ['버스 정류장'],
 403: ['천국의 문'],
 404: ['젊은 날의 초상'],
 405: ['7인의 사무라이'],
 406: ['새엄마는 외계인'],
 407: ['캠퍼스 군단'],
 408: ['그레이스토크'],
 409: ['윌로우'],
 410: ['이어 오브 드래곤'],
 411: ['이창'],
 412: ['천국보다 낯선'],
 413: ['첩혈가두'],
 414: ['촉산'],
 415: ['크레이머 대 크레이머'],
 416: ['7월 4일생'],
 417: ['코브라'],
 418: ['태양의 제국'],
 419: ['천금을 마다한 사나이'],
 420: ['좋은 친구들'],
 421: ['커튼 클럽'],
 422: ['트윈스'],
 423: ['도어즈'],
 424: ['특전 유보트'],
 425: ['복카치오 91'],
 426: ['홀리데이 킬러'],
 427: ['실버라도'],
 428: ['나의 사랑 나의 신부'],
 429: ['적과의 동침'],
 430: ['겨울 여자 2'],
 431: ['몽중인'],
 432: ['복수무정'],
 433: ['비처럼 음악처럼'],
 434: ['인어 공주'],
 435: ['천녀유혼'],
 436: ['타이페이 스토리'],
 437: ['패튼 대전차 군단'],
 438: ['포스트맨은 벨을 두 번 울린다'],
 439: ['제7의 봉인'],
 440: ['사랑의 용기'],
 441: ['천녀유혼 2 - 인간도'],
 442: ['뻐꾸기 둥지 위로 날아간 새'],
 443: ['사랑과 추억'],
 444: ['천사와 사랑을'],
 445: ['사랑과 슬픔의 맨하탄'],
 446: ['블랙 썬데이'],
 447: ['컬러 퍼플'],
 448: ['마지막 보이 스카웃'],
 449: ['파리에서의 마지막 탱고'],
 450: ['프라하의 봄'],
 451: [nan],
 452: ['파리 대왕'],
 453: ['파리 텍사스'],
 454: ['애마부인 4'],
 455: ['애마부인 5'],
 456: ['애마부인 6'],
 457: ['코러스 라인'],
 458: ['월 스트리트'],
 459: ['더티 해리'],
 460: ['더티 해리 2 - 이것이 법이다'],
 461: ['더티 해리 3 - 집행자'],
 462: ['더티 해리 4 - 써든 임팩트'],
 463: ['48시간'],
 464: ['48시간 2'],
 465: ['집시의 시간'],
 466: ['비치 바니즈'],
 467: ['자전거를 타고 온 연인'],
 468: ['나이트메어 2 - 프레디의 복수'],
 469: ['나이트메어 3 - 꿈의 전사'],
 470: ['나이트메어 4 - 꿈의 지배자'],
 471: ['나이트메어 5 - 꿈꾸는 아이들'],
 472: ['나이트메어 6 - 프레디 죽다'],
 473: ['JFK'],
 474: ['연인'],
 475: ['원초적 본능'],
 476: ['불을 찾아서'],
 477: ['비목'],
 478: ['폴리스 스토리'],
 479: ['파리 애마'],
 480: ['블루 라군'],
 481: ['사랑의 파도'],
 482: ['적 그리고 사랑 이야기'],
 483: ['아이다호'],
 484: ['나이아가라'],
 485: ['달마가 동쪽으로 간 까닭은?'],
 486: ['기쁜 우리 젊은 날'],
 487: ['사랑의 기적'],
 488: ['배트 21'],
 489: ['가을 날의 동화'],
 490: ['프랭키와 쟈니'],
 491: ['하타리'],
 492: ['애들이 줄었어요'],
 493: ['반도레로'],
 494: ['소권괴초 2 - 용등호약'],
 495: ['수탉'],
 496: [nan],
 497: ['유혹은 밤 그림자처럼'],
 498: ['벅시'],
 499: ['토탈 리콜'],
 500: ['김의 전쟁'],
 501: ['애란'],
 502: ['모두가 죽이고 싶던 여자'],
 503: ['이자벨 에버하트'],
 504: ['마이키 이야기 2'],
 505: ['우묵배미의 사랑'],
 506: ['장군의 아들 2'],
 507: ['장군의 아들 3'],
 508: ['딕 트레이시'],
 509: ['우뢰매'],
 510: ['내 사랑 동키호테'],
 511: ['백경'],
 512: ['영심이'],
 513: ['영구와 땡칠이'],
 514: ['블랙 에이리언'],
 515: ['밤 그리고 도시'],
 516: ['깃발 없는 기수'],
 517: ['깊고 푸른 밤'],
 518: ['아파치'],
 519: ['베를린 리포트'],
 520: ['꿈'],
 521: ['변강쇠 2'],
 522: ['칠수와 만수'],
 523: ['블루 하트'],
 524: ['쿼바디스'],
 525: ['마지막 사랑'],
 526: ['특경도룡'],
 527: ['천국으로 가는 장의사'],
 528: ['새'],
 529: ['죽음의 표적'],
 530: ['칼리굴라'],
 531: ['비공개'],
 532: ['부메랑'],
 533: ['더블 반담'],
 534: ['드레스드 투 킬'],
 535: ['모스키토 코스트'],
 536: ['베로니카의 이중 생활'],
 537: ['종횡사해'],
 538: ['와일드 오키드'],
 539: ['헨리 5세'],
 540: ['물 위를 걷는 여자'],
 541: ['깜보'],
 542: ['엠마뉴엘 3 - 굿바이 엠마뉴엘'],
 543: ['나일 살인사건'],
 544: ['개그맨'],
 545: ['깊은 밤 깊은 곳에'],
 546: ['개인 교수 2'],
 547: ['위험한 정사'],
 548: ['레이디 인 블랙'],
 549: ['8번가의 기적'],
 550: ['바람과 라이온'],
 551: ['피고인'],
 552: ['나의 밤은 당신의 낮보다 아름답다'],
 553: ['아제 아제 바라아제'],
 554: ['고령가 소년 살인사건'],
 555: ['뻘'],
 556: ['따귀 일곱대'],
 557: ['공작왕'],
 558: ['새앙쥐 상륙 작전'],
 559: ['비너스의 여름시'],
 560: ['로드 하우스'],
 561: ['가위손'],
 562: ['피셔 킹'],
 563: ['원 + 씩스'],
 564: ['베어'],
 565: ['누가 로져 래빗을 모함했나'],
 566: ['져지 걸'],
 567: ['공룡 선생'],
 568: ['카르멘'],
 569: ['마지막 전투'],
 570: ['마루타'],
 571: ['투 문 정션'],
 572: ['블레이드 러너'],
 573: ['섹스 거짓말 그리고 비디오테이프'],
 574: ['전선 위의 참새'],
 575: ['원스 어폰 어 타임 인 아메리카'],
 576: ['블루 스틸'],
 577: ['한니발'],
 578: ['킹콩 2'],
 579: ['학창 보고서'],
 580: ['비틀즈: 하드 데이즈 나이트'],
 581: ['분노의 역류'],
 582: ['하바나'],
 583: ['사랑이 머무는 곳에'],
 584: ['할리와 말보로 맨'],
 585: ['파리의 여인'],
 586: ['19번째 남자'],
 587: ['폭주 기관차']}